-- Таблица пользователей
CREATE TABLE IF NOT EXISTS users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL
);

-- Таблица категорий
CREATE TABLE IF NOT EXISTS categories (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

-- Таблица событий
CREATE TABLE IF NOT EXISTS events (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation TEXT NOT NULL,
    created_on TIMESTAMP NOT NULL,
    description TEXT,
    event_date TIMESTAMP NOT NULL,
    initiator_id INT NOT NULL,
    location_lat DOUBLE PRECISION NOT NULL,
    location_lon DOUBLE PRECISION NOT NULL,
    paid BOOLEAN NOT NULL,
    participant_limit INT,
    published_on TIMESTAMP,
    request_moderation BOOLEAN,
    state VARCHAR(32),
    title VARCHAR(255) NOT NULL,
    FOREIGN KEY (initiator_id) REFERENCES users(id)
);

-- Таблица запросов на участие
CREATE TABLE IF NOT EXISTS requests (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id INT NOT NULL,
    status VARCHAR(32) NOT NULL,
    requester_id INT NOT NULL,
    created TIMESTAMP NOT NULL,
    FOREIGN KEY (event_id) REFERENCES events(id),
    FOREIGN KEY (requester_id) REFERENCES users(id)
);

-- Таблица связи событий и категорий (многие ко многим)
CREATE TABLE IF NOT EXISTS events_categories (
   event_id INT NOT NULL,
   category_id INT NOT NULL,
   PRIMARY KEY (event_id, category_id),
   FOREIGN KEY (event_id) REFERENCES events(id),
   FOREIGN KEY (category_id) REFERENCES categories(id)
);

-- Подборки событий
CREATE TABLE IF NOT EXISTS compilation (
     id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     event_id INT NOT NULL,
     pinned BOOLEAN NOT NULL,
     title VARCHAR(255) NOT NULL,
     FOREIGN KEY (event_id) REFERENCES events(id)
);