-- Таблица пользователей
CREATE TABLE IF NOT EXISTS Users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL
);

-- Таблица категорий
CREATE TABLE IF NOT EXISTS Categories (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

-- Таблица событий
CREATE TABLE IF NOT EXISTS Events (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation VARCHAR(255) NOT NULL,
    createdOn TIMESTAMP NOT NULL,
    description TEXT,
    eventDate TIMESTAMP NOT NULL,
    initiator_id INT NOT NULL,
    location_lat DOUBLE PRECISION NOT NULL,
    location_lon DOUBLE PRECISION NOT NULL,
    paid BOOLEAN NOT NULL,
    participantLimit INT,
    publishedOn TIMESTAMP,
    requestModeration BOOLEAN,
    state VARCHAR(32),
    title VARCHAR(255) NOT NULL,
    FOREIGN KEY (initiator_id) REFERENCES Users(id)
);

-- Таблица запросов на участие
CREATE TABLE IF NOT EXISTS Requests (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id INT NOT NULL,
    status VARCHAR(32) NOT NULL,
    requester_id INT NOT NULL,
    created TIMESTAMP NOT NULL,
    FOREIGN KEY (event_id) REFERENCES Events(id),
    FOREIGN KEY (requester_id) REFERENCES Users(id)
);

-- Таблица связи событий и категорий (многие ко многим)
CREATE TABLE IF NOT EXISTS Events_Categories (
   event_id INT NOT NULL,
   category_id INT NOT NULL,
   PRIMARY KEY (event_id, category_id),
   FOREIGN KEY (event_id) REFERENCES Events(id),
   FOREIGN KEY (category_id) REFERENCES Categories(id)
);

-- Подборки событий
CREATE TABLE IF NOT EXISTS Compilation (
     id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     event_id INT NOT NULL,
     pinned BOOLEAN NOT NULL,
     title VARCHAR(255) NOT NULL,
     FOREIGN KEY (event_id) REFERENCES Events(id)
);