CREATE TABLE IF NOT EXISTS hits
(
    hit_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    app VARCHAR(32) NOT NULL,
    uri VARCHAR(128) NOT NULL,
    ip  VARCHAR(45) NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL
);